name: Terraform AWS Infrastructure

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: ap-south-1
  TF_IN_AUTOMATION: true

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Init
        run: terraform init

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan -out=planfile

      - name: Apply
        run: terraform apply "planfile"